-- Step 1: Start the psql server with sudo service postgresql start
-- Step 2: Run command: psql -d doggos -f init.sql

DROP TABLE IF EXISTS dogs;
DROP TABLE IF EXISTS quotes;

CREATE TABLE dogs (
  id SERIAL PRIMARY KEY, 
  name TEXT,
  DOB DATE,
  about TEXT,
  status INTEGER
);

CREATE TABLE quotes (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  quote TEXT,
  quoter_id INTEGER
);

INSERT INTO dogs (name, DOB, about, status) VALUES
('Jimmy','2020-04-05','expedite user-centric e-markets',1),
('Mirilla','2020-05-16','generate e-business metrics',3),
('Gill','2020-07-29','transform clicks-and-mortar vortals',2),
('Gerrilee','2020-11-08','syndicate strategic ROI',3),
('Shannon','2020-05-27','scale ubiquitous ROI',3),
('Hal','2020-08-08','enhance vertical synergies',1),
('Eziechiele','2020-03-18','productize robust architectures',2),
('Stavro','2020-04-16','expedite seamless applications',1),
('Corbin','2020-12-30','reintermediate bleeding-edge relationships',1),
('Nicoline','2020-04-17','cultivate global action-items',3),
('Rem','2020-07-14','iterate transparent infrastructures',3),
('August','2020-05-07','redefine clicks-and-mortar models',3),
('Brocky','2020-05-03','incentivize robust action-items',2),
('Clim','2020-09-30','transition cutting-edge schemas',2),
('Persis','2020-07-18','benchmark robust users',2),
('Frederich','2020-11-23','orchestrate bricks-and-clicks functionalities',1),
('Red','2020-02-27','optimize revolutionary eyeballs',3),
('Nada','2020-08-05','grow ubiquitous ROI',1),
('Jeni','2020-11-02','repurpose cross-platform web services',2),
('Elisabet','2020-06-01','harness visionary web services',3),
('Bree','2020-09-24','unleash scalable architectures',3),
('Dion','2020-01-25','exploit seamless infrastructures',1),
('Evangelia','2020-07-09','deliver scalable schemas',2),
('Dud','2020-07-02','morph turn-key mindshare',2),
('Allina','2020-12-30','productize virtual paradigms',1),
('Chas','2020-11-22','monetize collaborative ROI',3),
('Carmelina','2020-10-10','productize wireless infrastructures',2),
('Paulo','2020-09-28','implement strategic networks',2),
('Alta','2020-09-28','target web-enabled content',3),
('Alida','2020-11-02','enable world-class technologies',3),
('Ugo','2020-04-06','utilize interactive experiences',3),
('Harold','2020-09-12','streamline B2B models',1),
('Cindie','2020-09-18','transform mission-critical deliverables',3),
('Franciskus','2020-05-12','aggregate global e-commerce',3),
('Chance','2020-11-14','leverage innovative technologies',3),
('Elia','2020-11-28','aggregate holistic e-services',3),
('Nelson','2020-12-03','grow world-class bandwidth',2),
('Hortense','2020-05-04','optimize distributed users',2),
('Roxane','2020-04-01','target 24/7 initiatives',3),
('Suzi','2020-03-19','embrace integrated eyeballs',3),
('Mandi','2020-10-07','strategize dynamic paradigms',1),
('Michelina','2020-01-07','engineer 24/7 experiences',1),
('Garnet','2020-03-15','engineer 24/365 schemas',3),
('Aline','2020-08-27','reintermediate B2B supply-chains',3),
('Georgina','2020-07-26','repurpose cutting-edge mindshare',2),
('Emmott','2020-05-10','benchmark bleeding-edge portals',3),
('Odell','2020-11-11','facilitate next-generation vortals',1),
('Trixie','2020-09-17','exploit out-of-the-box synergies',3),
('Krystalle','2020-11-17','orchestrate ubiquitous vortals',1),
('Simmonds','2020-12-04','incubate impactful communities',2),
('Twila','2020-02-17','deploy granular schemas',3),
('Mathian','2020-10-15','redefine clicks-and-mortar paradigms',2),
('Alexei','2020-06-17','evolve 24/7 portals',1),
('Hercules','2020-08-08','transform value-added e-markets',2),
('Liz','2020-02-05','empower turn-key systems',1),
('Seymour','2020-08-05','e-enable collaborative web-readiness',2),
('Loydie','2020-04-04','scale proactive content',1),
('Kelwin','2020-12-26','transition turn-key web services',1),
('Paloma','2020-04-09','transition B2C deliverables',1),
('Teodor','2020-10-04','seize integrated systems',1),
('Caressa','2020-07-17','target value-added networks',1),
('Madeleine','2020-01-22','facilitate ubiquitous vortals',3),
('Giovanni','2020-12-02','mesh distributed methodologies',1),
('Renee','2020-01-05','maximize cutting-edge metrics',1),
('Jilli','2020-12-01','integrate compelling e-business',3),
('Northrup','2020-07-20','leverage plug-and-play eyeballs',2),
('Tabbatha','2020-11-14','expedite cross-platform eyeballs',1),
('Opal','2020-06-07','strategize wireless paradigms',3),
('Valma','2020-07-05','deliver 24/7 initiatives',3),
('Halette','2020-02-08','e-enable B2B bandwidth',1),
('Evangelin','2020-08-27','drive open-source users',2),
('Idalia','2020-12-24','synthesize global platforms',1),
('Bryn','2020-07-15','cultivate visionary experiences',3),
('Mikael','2020-04-05','optimize holistic eyeballs',1),
('Brennan','2020-09-05','mesh dot-com technologies',3),
('Madelena','2020-07-28','transform bricks-and-clicks web services',2),
('Desiree','2020-02-27','exploit viral mindshare',1),
('Jayson','2020-08-11','streamline customized metrics',3),
('Borden','2020-11-15','disintermediate front-end eyeballs',1),
('Gaynor','2020-03-30','brand magnetic channels',2),
('Duffy','2020-01-05','innovate mission-critical e-commerce',3),
('Christabel','2020-02-02','streamline holistic infomediaries',2),
('Llewellyn','2020-12-06','iterate clicks-and-mortar content',1),
('Vanna','2020-08-02','aggregate sexy markets',2),
('Luciano','2020-10-11','unleash vertical e-commerce',2),
('Panchito','2020-12-14','target global initiatives',3),
('Fania','2020-02-16','seize frictionless portals',3),
('Lexie','2020-08-09','architect ubiquitous experiences',3),
('Betsey','2020-04-23','integrate granular action-items',1),
('Yulma','2020-06-30','harness revolutionary synergies',1),
('Cher','2020-01-04','enable dynamic web services',3),
('Giff','2020-04-06','iterate cross-platform niches',3),
('Vinni','2020-04-10','visualize e-business functionalities',1),
('Karlotte','2020-05-21','evolve virtual metrics',1),
('Lauritz','2020-03-10','target efficient channels',1),
('Catherina','2020-12-05','envisioneer rich markets',3),
('Janel','2020-12-06','iterate interactive systems',2),
('Siegfried','2020-05-17','engineer synergistic paradigms',3),
('Emmit','2020-05-01','disintermediate transparent ROI',2),
('Herrick','2020-10-03','iterate global bandwidth',1);

INSERT INTO quotes (quote, quoter_id) VALUES
('Genius is one percent inspiration and ninety-nine percent perspiration.',49),
('You can observe a lot just by watching.',71),
('A house divided against itself cannot stand.',9),
('Difficulties increase the nearer we get to the goal.',31),
('Fate is in your hands and no one elses',24),
('Be the chief but never the lord.',44),
('Nothing happens unless first we dream.',23),
('Well begun is half done.',94),
('Life is a learning experience, only if you learn.',89),
('Self-complacency is fatal to progress.',30),
('Peace comes from within. Do not seek it without.',94),
('What you give is what you get.',45),
('We can only learn to love by loving.',15),
('Life is change. Growth is optional. Choose wisely.',63),
('You''ll see it when you believe it.',6),
('Today is the tomorrow we worried about yesterday.',95),
('It''s easier to see the mistakes on someone else''s paper.',55),
('Every man dies. Not every man really lives.',44),
('To lead people walk behind them.',13),
('Having nothing, nothing can he lose.',3),
('Trouble is only opportunity in work clothes.',63),
('A rolling stone gathers no moss.',42),
('Ideas are the beginning points of all fortunes.',94),
('Everything in life is luck.',4),
('Doing nothing is better than being busy doing nothing.',95),
('Trust yourself. You know more than you think you do.',65),
('Study the past, if you would divine the future.',78),
('The day is already blessed, find peace within it.',91),
('From error to error one discovers the entire truth.',74),
('Well done is better than well said.',45),
('Bite off more than you can chew, then chew it.',48),
('Work out your own salvation. Do not depend on others.',90),
('One today is worth two tomorrows.',34),
('Once you choose hope, anythings possible.',38),
('God always takes the simplest way.',70),
('One fails forward toward success.',6),
('From small beginnings come great things.',63),
('Learning is a treasure that will follow its owner everywhere',77),
('Be as you wish to seem.',65),
('The world is always in movement.',53),
('Never mistake activity for achievement.',1),
('What worries you masters you.',70),
('One faces the future with ones past.',86),
('Goals are the fuel in the furnace of achievement.',6),
('Who sows virtue reaps honour.',59),
('Be kind whenever possible. It is always possible.',8),
('Talk doesn''t cook rice.',77),
('He is able who thinks he is able.',30),
('A goal without a plan is just a wish.',1),
('To succeed, we must first believe that we can.',54),
('Learn from yesterday, live for today, hope for tomorrow.',28),
('A weed is no more than a flower in disguise.',62),
('Do, or do not. There is no try.',39),
('All serious daring starts from within.',70),
('The best teacher is experience learned from failures.',57),
('Think how hard physics would be if particles could think.',30),
('Love is the flower you''ve got to let grow.',74),
('Don''t wait. The time will never be just right.',92),
('Time is the wisest counsellor of all.',49),
('You give before you get.',65),
('Wisdom begins in wonder.',19),
('Without courage, wisdom bears no fruit.',35),
('Change in all things is sweet.',50),
('What you fear is that which requires action to overcome.',60),
('When performance exceeds ambition, the overlap is called success.',24),
('When deeds speak, words are nothing.',11),
('Real magic in relationships means an absence of judgement of others.',49),
('I never think of the future. It comes soon enough.',54),
('Skill to do comes of doing.',43),
('Wisdom is the supreme part of happiness.',10),
('I believe that every person is born with talent.',88),
('Important principles may, and must, be inflexible.',5),
('The undertaking of a new action brings new strength.',85),
('The years teach much which the days never know.',81),
('Our distrust is very expensive.',84),
('All know the way; few actually walk it.',94),
('Great talent finds happiness in execution.',80),
('Faith in oneself is the best and safest course.',17),
('Courage is going from failure to failure without losing enthusiasm.',51),
('The two most powerful warriors are patience and time.',71),
('Anticipate the difficult by managing the easy.',54),
('Those who are free of resentful thoughts surely find peace.',6),
('A short saying often contains much wisdom.',62),
('It takes both sunshine and rain to make a rainbow.',5),
('A beautiful thing is never perfect.',27),
('Only do what your heart tells you.',53),
('Life is movement-we breathe, we eat, we walk, we move!',17),
('No one can make you feel inferior without your consent.',40),
('Argue for your limitations, and sure enough theyre yours.',56),
('Luck is what happens when preparation meets opportunity.',61),
('Victory belongs to the most persevering.',46),
('Love all, trust a few, do wrong to none.',4),
('In order to win, you must expect to win.',13),
('A goal is a dream with a deadline.',76),
('You can do it if you believe you can!',46),
('Set your goals high, and don''t stop till you get there.',24),
('Every new day is another chance to change your life.',67),
('Smile, breathe, and go slowly.',65),
('Nobody will believe in you unless you believe in yourself.',52),
('Do more than dream: work.',66),
('No man was ever wise by chance.',40),
('Some pursue happiness, others create it.',64),
('He that is giddy thinks the world turns round.',15),
('Don''t ruin the present with the ruined past.',54),
('Do something wonderful, people may imitate it.',29),
('We do what we do because we believe.',10),
('Do one thing every day that scares you.',64),
('If you cannot be silent be brilliant and thoughtful.',24),
('Who looks outside, dreams; who looks inside, awakes.',54),
('What we think, we become.',14),
('The shortest answer is doing.',10),
('All our knowledge has its origins in our perceptions.',49),
('The harder you fall, the higher you bounce.',76),
('Trusting our intuition often saves us from disaster.',84),
('Truth is powerful and it prevails.',88),
('Light tomorrow with today!',26),
('Silence is a fence around wisdom.',22),
('Society develops wit, but its contemplation alone forms genius.',31),
('The simplest things are often the truest.',40),
('Everyone smiles in the same language.',2),
('Yesterday I dared to struggle. Today I dare to win.',19),
('No alibi will save you from accepting the responsibility.',68),
('If you can dream it, you can do it.',91),
('It is better to travel well than to arrive.',87),
('Life shrinks or expands in proportion to one''s courage.',45),
('You have to believe in yourself.',75),
('Our intention creates our reality.',5),
('Silence is a true friend who never betrays.',95),
('Character develops itself in the stream of life.',73),
('From little acorns mighty oaks do grow.',81),
('You can''t stop the waves, but you can learn to surf.',25),
('Reality does not conform to the ideal, but confirms it.',80),
('Speak low, if you speak love.',51),
('A really great talent finds its happiness in execution.',83),
('Reality leaves a lot to the imagination.',93),
('The greatest remedy for anger is delay.',22),
('Growth itself contains the germ of happiness.',4),
('You can do what''s reasonable or you can decide what''s possible.',53),
('Nothing strengthens authority so much as silence.',3),
('Wherever you go, go with all your heart.',41),
('The only real valuable thing is intuition.',54),
('Good luck is another name for tenacity of purpose.',63),
('Rainbows apologize for angry skies.',13),
('Friendship isn''t a big thing. It''s a million little things.',7),
('Time is the most valuable thing a man can spend.',95),
('Whatever happens, take responsibility.',26),
('Experience is simply the name we give our mistakes.',27),
('I think and that is all that I am.',4),
('A good plan today is better than a perfect plan tomorrow.',65),
('If the shoe doesn''t fit, must we change the foot?',41),
('Each day provides its own gifts.',77),
('While we stop to think, we often miss our opportunity.',35),
('Life isn''t about finding yourself. Life is about creating yourself.',87),
('To bring anything into your life, imagine that it''s already there.',2),
('Begin to weave and God will give you the thread.',8),
('The more you know yourself, the more you forgive yourself.',30),
('Someone remembers, someone cares; your name is whispered in someone''s prayers.',73),
('Without faith, nothing is possible. With it, nothing is impossible.',14),
('Once we accept our limits, we go beyond them.',80),
('Don''t be pushed by your problems; be led by your dreams.',14),
('Whatever we expect with confidence becomes our own self-fulfilling prophecy.',1),
('Everything you can imagine is real.',67),
('Fear is a darkroom where negatives develop.',88),
('The truest wisdom is a resolute determination.',33),
('Life is the flower for which love is the honey.',88),
('Freedom is the right to live as we wish.',55),
('Change your thoughts, change your life!',38),
('Never ignore a gut feeling, but never believe that it''s enough.',60),
('Loss is nothing else but change,and change is Natures delight.',50),
('Someone is special only if you tell them.',44),
('Today is the tomorrow you worried about yesterday.',10),
('There is no way to happiness, happiness is the way.',21),
('The day always looks brighter from behind a smile.',4),
('A stumble may prevent a fall.',37),
('He who talks more is sooner exhausted.',78),
('He who is contented is rich.',20),
('What we achieve inwardly will change outer reality.',11),
('Our strength grows out of our weaknesses.',48),
('We must become the change we want to see.',50),
('Happiness is found in doing, not merely possessing.',48),
('Put your future in good hands : your own.',38),
('We choose our destiny in the way we treat others.',67),
('No snowflake in an avalanche ever feels responsible.',54),
('Fortune favours the brave.',74),
('I believe in one thing only, the power of human will.',94),
('The best way out is always through.',36),
('The mind unlearns with difficulty what it has long learned.',1),
('I destroy my enemies when I make them my friends.',18),
('No garden is without its weeds.',72),
('There is no failure except in no longer trying.',18),
('Kind words will unlock an iron door.',61),
('Problems are only opportunities with thorns on them.',78),
('Life is just a chance to grow a soul.',90),
('Mountains cannot be surmounted except by winding paths.',23),
('May our hearts garden of awakening bloom with hundreds of flowers.',20),
('Fortune befriends the bold.',27),
('Keep true to the dreams of thy youth.',68),
('You''re never a loser until you quit trying.',80),
('Science is organized knowledge. Wisdom is organized life.',42),
('Knowing is not enough; we must apply!',34),
('Strong beliefs win strong men, and then make them stronger.',3),
('Autumn is a second spring when every leaf is a flower.',66),
('If you surrender to the wind, you can ride it.',20),
('Keep yourself to the sunshine and you cannot see the shadow.',67),
('Write your plans in pencil and give God the eraser.',76),
('Inspiration exists, but it has to find us working.',84),
('Pick battles big enough to matter, small enough to win.',93),
('Don''t compromise yourself. You are all you''ve got.',16),
('A short saying oft contains much wisdom.',87),
('Difficulties are things that show a person what they are.',11),
('When you doubt your power, you give power to your doubt.',65),
('The cause is hidden. The effect is visible to all.',10),
('A prudent question is one half of wisdom.',45),
('The path to success is to take massive, determined action.',59),
('I allow my intuition to lead my path.',59),
('Nature takes away any faculty that is not used.',79),
('If you wish to be a writer, write.',53),
('There is no way to prosperity, prosperity is the way.',67),
('Either you run the day or the day runs you.',57),
('Better be ignorant of a matter than half know it.',16),
('Follow your instincts. That is where true wisdom manifests itself.',9),
('There never was a good knife made of bad steel.',65),
('To accomplish great things, we must dream as well as act.',88),
('Patience is the companion of wisdom.',32),
('The mind is everything. What you think you become.',95),
('To enjoy life, we must touch much of it lightly.',21),
('To fly, we have to have resistance.',46),
('What you see depends on what you''re looking for.',77),
('The heart has its reasons which reason knows not of.',44),
('Be great in act, as you have been in thought.',26),
('Imagination rules the world.',55),
('Kind words do not cost much. Yet they accomplish much.',72),
('There is no greater harm than that of time wasted.',88),
('Intuition will tell the thinking mind where to look next.',40),
('Worry gives a small thing a big shadow.',54),
('Fears are nothing more than a state of mind.',44),
('The journey of a thousand miles begins with one step.',86),
('Efficiency is doing things right; effectiveness is doing the right things.',66),
('Blaze with the fire that is never extinguished.',55),
('Don''t cry because it''s over. Smile because it happened.',53),
('No is easier to do. Yes is easier to say.',63),
('To be wrong is nothing unless you continue to remember it.',46),
('Yesterdays home runs don''t win today''s games.',76),
('Silence is deep as Eternity, Speech is shallow as Time.',77),
('Don''t smother each other. No one can grow in the shade.',40),
('An ant on the move does more than a dozing ox',49),
('You can''t shake hands with a clenched fist.',49),
('A good decision is based on knowledge and not on numbers.',83),
('The cautious seldom err.',18),
('If there is no struggle, there is no progress.',95),
('Where there is great love, there are always miracles.',69),
('Time you enjoy wasting, was not wasted.',73),
('Every problem has a gift for you in its hands.',73),
('Sadness flies away on the wings of time.',57),
('I have often regretted my speech, never my silence.',24),
('Never put off till tomorrow what you can do today.',85),
('Minds are like parachutes. They only function when open.',10),
('If a man does his best, what else is there?',19),
('The secret of success is constancy to purpose.',81),
('Life is a progress, and not a station.',29),
('All seasons are beautiful for the person who carries happiness within.',56),
('To avoid criticism, do nothing, say nothing, be nothing.',84),
('All things change; nothing perishes.',3),
('Absence makes the heart grow fonder.',37),
('Imagination is the highest kite one can fly.',1),
('The beginning of knowledge is the discovery of something we do not understand.',4),
('Love doesn''t make the world go round, love is what makes the ride worthwhile.',31),
('Whenever you have eliminated the impossible, whatever remains, however improbable, must be the truth.',12),
('Good timber does not grow with ease; the stronger the wind, the stronger the trees.',81),
('I believe that we are fundamentally the same and have the same basic potential.',82),
('The winds and waves are always on the side of the ablest navigators.',16),
('The future belongs to those who believe in the beauty of their dreams.',18),
('To get something you never had, you have to do something you never did.',3),
('Be thankful when you don''t know something for it gives you the opportunity to learn.',11),
('Strength does not come from physical capacity. It comes from an indomitable will.',61),
('Each misfortune you encounter will carry in it the seed of tomorrows good luck.',44),
('To forgive is to set a prisoner free and realize that prisoner was you.',33),
('In separateness lies the world''s great misery, in compassion lies the world''s true strength.',6),
('By believing passionately in something that does not yet exist, we create it.',29),
('Letting go isn''t the end of the world; it''s the beginning of a new life.',18),
('All the great performers I have worked with are fuelled by a personal dream.',67),
('One of the advantages of being disorderly is that one is constantly making exciting discoveries.',54),
('I never see what has been done; I only see what remains to be done.',14),
('Begin at once to live and count each separate day as a separate life.',85),
('If you don''t know where you are going, you will probably end up somewhere else.',87),
('It is not so important to know everything as to appreciate what we learn.',53),
('The bird of paradise alights only upon the hand that does not grasp.',42),
('Think as a wise man but communicate in the language of the people.',90),
('Practice yourself, for heavens sake in little things, and then proceed to greater.',26),
('If one does not know to which port is sailing, no wind is favorable.',19),
('Our greatest glory is not in never failing but rising everytime we fall.',6),
('Being right is highly overrated. Even a stopped clock is right twice a day.',29),
('To be upset over what you don''t have is to waste what you do have.',87),
('If we did the things we are capable of, we would astound ourselves.',76),
('Nothing in life is to be feared. It is only to be understood.',67),
('Successful people ask better questions, and as a result, they get better answers.',8),
('Love is not blind; it simply enables one to see things others fail to see.',51),
('Life is a process. We are a process. The universe is a process.',79),
('I think somehow we learn who we really are and then live with that decision.',17),
('We learn what we have said from those who listen to our speaking.',25),
('A little knowledge that acts is worth infinitely more than much knowledge that is idle.',76),
('If you get up one more time than you fall, you will make it through.',82),
('The doors we open and close each day decide the lives we live.',90),
('The worst bankrupt in the world is the person who has lost his enthusiasm.',51),
('Happiness comes when your work and words are of benefit to yourself and others.',42),
('Don''t focus on making the right decision, focus on making the decision the right one.',11),
('Everything is perfect in the universe, even your desire to improve it.',28),
('The universe is full of magical things, patiently waiting for our wits to grow sharper.',38),
('Just as a candle cannot burn without fire, men cannot live without a spiritual life.',2),
('A thing long expected takes the form of the unexpected when at last it comes.',94),
('Action may not always bring happiness; but there is no happiness without action.',24),
('I don''t believe in failure. It is not failure if you enjoyed the process.',94),
('What you do not want done to yourself, do not do to others.',77),
('Short words are best and the old words when short are best of all.',90),
('If you light a lamp for somebody, it will also brighten your path.',92),
('I have done my best: that is about all the philosophy of living one needs.',32),
('Through perseverance many people win success out of what seemed destined to be certain failure.',51),
('Give thanks for the rain of life that propels us to reach new horizons.',23),
('Love is just a word until someone comes along and gives it meaning.',66),
('We all have problems. The way we solve them is what makes us different.',13),
('The secret to a rich life is to have more beginnings than endings.',63),
('It is only when the mind and character slumber that the dress can be seen.',81),
('If you don''t like something, change it. If you can''t change it, change your attitude.',79),
('Reviewing what you have learned and learning anew, you are fit to be a teacher.',18),
('The world is a book, and those who do not travel read only a page.',44),
('So long as a person is capable of self-renewal they are a living being.',41),
('I''m not afraid of storms, for Im learning how to sail my ship.',76),
('Think for yourselves and let others enjoy the privilege to do so too.',66),
('How we spend our days is, of course, how we spend our lives.',46),
('It has never been my object to record my dreams, just to realize them.',65),
('The most complicated achievements of thought are possible without the assistance of consciousness.',17),
('Be miserable. Or motivate yourself. Whatever has to be done, it''s always your choice.',78),
('Most great people have attained their greatest success just one step beyond their greatest failure.',25),
('If you think you can, you can. And if you think you can''t, you''re right.',32),
('Better to have loved and lost, than to have never loved at all.',65),
('Everyone thinks of changing the world, but no one thinks of changing himself.',81),
('The best way to pay for a lovely moment is to enjoy it.',53),
('You have enemies? Good. That means you''ve stood up for something, sometime in your life.',95),
('Slow down and everything you are chasing will come around and catch you.',50),
('Your worst enemy cannot harm you as much as your own unguarded thoughts.',41),
('I always wanted to be somebody, but I should have been more specific.',82),
('Yeah we all shine on, like the moon, and the stars, and the sun.',55),
('Knowledge is a process of piling up facts; wisdom lies in their simplification.',50),
('Life is like riding a bicycle. To keep your balance you must keep moving.',15),
('We should all be thankful for those people who rekindle the inner spirit.',9),
('Opportunity is missed by most because it is dressed in overalls and looks like work.',87),
('Feeling and longing are the motive forces behind all human endeavor and human creations.',4),
('In the end we retain from our studies only that which we practically apply.',18),
('If you correct your mind, the rest of your life will fall into place.',91),
('The world makes way for the man who knows where he is going.',25),
('When your desires are strong enough you will appear to possess superhuman powers to achieve.',64),
('Patience and perseverance have a magical effect before which difficulties disappear and obstacles vanish.',42),
('I cannot make my days longer so I strive to make them better.',58),
('Tension is who you think you should be. Relaxation is who you are.',33),
('Never bend your head. Always hold it high. Look the world right in the eye.',34),
('One who gains strength by overcoming obstacles possesses the only strength which can overcome adversity.',70),
('We cannot do everything at once, but we can do something at once.',44),
('You have to do your own growing no matter how tall your grandfather was.',27),
('Invent your world. Surround yourself with people, color, sounds, and work that nourish you.',1),
('It is fatal to enter any war without the will to win it.',89),
('Be what you are. This is the first step toward becoming better than you are.',50),
('There is nothing in a caterpillar that tells you it''s going to be a butterfly.',76),
('Love and compassion open our own inner life, reducing stress, distrust and loneliness.',78),
('Ideals are an imaginative understanding of that which is desirable in that which is possible.',41),
('The superior man is satisfied and composed; the mean man is always full of distress.',2),
('If you spend too much time thinking about a thing, you''ll never get it done.',70),
('The way is not in the sky. The way is in the heart.',63),
('Most people are about as happy as they make up their minds to be',34),
('Three things cannot be long hidden: the sun, the moon, and the truth.',7),
('More often than not, anger is actually an indication of weakness rather than of strength.',11),
('Before you put on a frown, make absolutely sure there are no smiles available.',46),
('A man of ability and the desire to accomplish something can do anything.',20),
('You, yourself, as much as anybody in the entire universe, deserve your love and affection.',5),
('It is not uncommon for people to spend their whole life waiting to start living.',3),
('Don''t be afraid to go out on a limb. That''s where the fruit is.',88),
('Wicked people are always surprised to find ability in those that are good.',21),
('Life is so constructed that an event does not, cannot, will not, match the expectation.',73),
('If you change the way you look at things, the things you look at change.',73),
('No man can succeed in a line of endeavor which he does not like.',19),
('You will not be punished for your anger, you will be punished by your anger.',12),
('Don''t judge each day by the harvest you reap but by the seeds you plant.',59),
('They say that time changes things, but you actually have to change them yourself.',35),
('Never apologize for showing feelings. When you do so, you apologize for the truth.',22),
('The truth you believe and cling to makes you unavailable to hear anything new.',78),
('Adversity has the effect of eliciting talents, which in prosperous circumstances would have lain dormant.',3),
('If you spend your whole life waiting for the storm, you''ll never enjoy the sunshine.',26),
('The only limit to our realization of tomorrow will be our doubts of today.',35),
('Every action of our lives touches on some chord that will vibrate in eternity.',29),
('Shoot for the moon. Even if you miss, you''ll land among the stars.',60),
('It does not matter how slowly you go as long as you do not stop.',72),
('Every day may not be good, but there''s something good in every day.',20),
('Most folks are about as happy as they make up their minds to be.',27),
('If you would take, you must first give, this is the beginning of intelligence.',3),
('Some people think it''s holding that makes one strong, sometimes it''s letting go.',19),
('It is on our failures that we base a new and different and better success.',88),
('Quality is never an accident; it is always the result of intelligent effort.',82),
('To study and not think is a waste. To think and not study is dangerous.',40),
('Life is a succession of lessons, which must be lived to be understood.',54),
('Time changes everything except something within us which is always surprised by change.',33);